<a href="https://colab.research.google.com/github/WookwonShim/data-analysis/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fuctions for Matrices

In [ ]:
def matrix_multiplication(A, B):
    # Check if multiplication is possible
    if len(A[0]) != len(B):
        raise ValueError("Num of cols in A must be equal to the num of rows in B")

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    # Perform matrix multiplication
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

# Example matrices
A = [
    [1, 2, 0],
    [2, 3, 3]
]

B = [
    [2, 1, 1],
    [3, 3, 2],
    [1, 0, 0]
]

# Perform multiplication
result = matrix_multiplication(A, B)

# Print the result
print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

print("\nResult of A * B:")
for row in result:
    print(row)

Matrix A:
[1, 2, 0]
[2, 3, 3]

Matrix B:
[2, 1, 1]
[3, 3, 2]
[1, 0, 0]

Result of A * B:
[8, 7, 5]
[16, 11, 8]


In [ ]:
def matrix_multiplication(A, B):
  # Define the properties of the matrices
  num_of_rows_A = len(A)    # number of rows in A
  num_of_cols_A = len(A[0]) # number of columns in A
  num_of_rows_B = len(B)    # number of rows in B
  num_of_cols_B = len(B[0]) # number of columns in B

  if num_of_cols_A != num_of_rows_B:
    raise ValueError("")

  # Initialize the result matrix with zeros
  result_matrix = [[0 for _ in range(num_of_cols_B)] for _ in range(num_of_rows_A)]

  return result_matrix

In [ ]:
A = [
    [1, 2, 0],
    [2, 3, 3]
]

B = [
    [2, 1, 1],
    [3, 3, 2],
    [1, 0, 0]
]

matrix_multiplication(A, B)

[[0, 0, 0], [0, 0, 0]]

In [ ]:
import numpy as np

def gauss_jordan_elimination(matrix):
    # Convert the input matrix to a numpy array for easier manipulation
    A = np.array(matrix, dtype=float)
    rows, cols = A.shape

    # Forward phase: Convert to row echelon form (REF)
    for i in range(rows):
        # Find the pivot element
        pivot = A[i, i]
        if pivot == 0:
            for k in range(i + 1, rows):
                if A[k, i] != 0:
                    # Swap the rows
                    A[[i, k]] = A[[k, i]]
                    pivot = A[i, i]
                    break

        # Make the pivot element 1
        A[i] = A[i] / pivot

        # Eliminate the elements below the pivot
        for j in range(i + 1, rows):
            A[j] = A[j] - A[j, i] * A[i]

    # Backward phase: Convert to reduced row echelon form (RREF)
    for i in range(rows - 1, -1, -1):
        # Eliminate the elements above the pivot
        for j in range(i - 1, -1, -1):
            A[j] = A[j] - A[j, i] * A[i]

    return A

# Example usage:
matrix = [
    [2, 1, -1, 8],
    [-3, -1, 2, -11],
    [-2, 1, 2, -3]
]
rref_matrix = gauss_jordan_elimination(matrix)
print(rref_matrix)


[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [-0. -0.  1. -1.]]


# Working With Linear Systems in Python

## Working With Vectors and Matrices Using NumPy

In [ ]:
import scipy
import numpy as np

A vector is a mathematical entity used to represent physical quantities that have both magnitude and direction.

In [ ]:
A = np.array([
    [1, 2],
     [3, 4],
      [5, 6]
    ])
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
v = np.array(
    [1, 2, 3] # a one-dimensional vector.
)
v

array([1, 2, 3])

In [ ]:
v.shape # a one-dimensional array (num of elements).

(3,)

In [ ]:
v2 = np.array(
    [[1, 2, 3]] # a two-dimensional row vector.
)
v2

array([[1, 2, 3]])

In [ ]:
v2.shape # a two-dimensional array (num of rows, num of cols). a nested list.

(1, 3)

In [ ]:
v3 = np.array(
    [[1], [2], [3]] # a two-dimensional column vector.
)
v3

array([[1],
       [2],
       [3]])

In [ ]:
v3.shape

(3, 1)

In [ ]:
v4 = np.array([1, 2, 3]).reshape(3, 1) # even though non-nested array, it creates a two dimensional array due to .reshape(3, 1).
v4

array([[1],
       [2],
       [3]])

In [ ]:
v5 = np.array([1, 2, 3]).reshape(-1, 1) # -1 as an argument
v5

array([[1],
       [2],
       [3]])

In [ ]:
np.zeros((3, 2)) # a tuple as an argument indicating (row, col). a float by default.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3, 2), dtype=int) # a tuple as an argument indicating (row, col).

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.random.rand(3, 2)

array([[0.04173374, 0.04163868],
       [0.91340744, 0.21541485],
       [0.74091387, 0.13567172]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
v = np.array([5, 6]).reshape(-1, 1)
A @ v # matrix multiplication

array([[17],
       [39]])

In [4]:
# Using scipy.linalg.solve()

import numpy as np
from scipy import linalg
A = np.array(
    [
        [3, 2],
        [2, -1]
    ]
) # create the coefficients matrix as a NumPy array and call it A.

b = np.array([12, 1]).reshape(-1, 1) # create the independent terms vector using a NumPy array called b.

x = linalg.solve(A, b) # call linalg.solve() to solve the linear system characterized by A and b, with the result stored in x
x

array([[2.],
       [3.]])


## Solving a Practical Problem: Building a Meal Plan

One sort of problem that you would generally solve with linear systems is when you need to find the proportions of components needed to obtain a certain mixture.

For that, assume that a balanced diet should include the following:

* 170 units of vitamin A
* 180 units of vitamin B
* 140 units of vitamin C
* 180 units of vitamin D
* 350 units of vitamin E

Your task is to find the quantities of each different food in order to obtain the specified amounts of the necessary vitamins. In the following table, you have the results of analyzing one gram of each food in terms of units of each vitamin:

| **Food** | **Vitamin A** | **Vitamin B** | **Vitamin C** | **Vitamin D** | **Vitamin E** |
|--- | --- | --- | --- | --- | --- |
| #1 | 1 | 10 | 1 | 2 | 2 |
| #2 | 9 | 1 | 0 | 1 | 1 |
| #3 | 2 | 2 | 5 | 1 | 2 |
| #4 | 1 | 1 | 1 | 2 | 13 |
| #5 | 1 | 1 | 1 | 9 | 2 |

In [9]:
A = np.array(
    [
        [1, 9, 2, 1, 1],
        [10, 1, 2, 1, 1],
        [1, 0, 5, 1, 1],
        [2, 1, 1, 2, 9],
        [2, 1, 2, 13, 2]

    ]
)

b = np.array(
    [170, 180, 140, 180, 350]
).reshape(-1, 1)

x = linalg.solve(A, b)
x

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])